---
apiVersion: v1
kind: Service
metadata:
  name: takehome
  labels:
    app: takehome
spec:
  type: NodePort
  selector:
    app: takehome
  ports:
    - protocol: TCP
      port: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takehome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takehome
  template:
    metadata:
      labels:
        app: takehome
    spec:
      containers:
        - name: takehome
          image: qyodeveloper/takehomeapp:1.1
          ports:
            - containerPort: 8080